<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.AI.Extensions.OpenAI" />
    <PackageReference Include="Azure.AI.Projects" />
    <PackageReference Include="Azure.AI.Projects.Agents" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" />
    <PackageReference Include="Azure.Search.Documents" />
    <PackageReference Include="DotNetEnv" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" />
    <PackageReference Include="OpenTelemetry" />
  </ItemGroup>
</Project>
